/* Tự động sinh bởi YouTube Channel Sync. Không chứa OAuth token hoặc client secret. */
(function (w) {
  'use strict';
  var data = {
  "schemaVersion": 1,
  "source": "YouTube Data API v3 - Local OAuth",
  "generatedAt": "2026-07-24T10:47:41.091512Z",
  "channel": {
    "id": "UCSISnv85eEjpBBBWxH2sgmA",
    "title": "Tự Nhiên Hiểu Chuyện",
    "handle": "@tunhienhieuchuyen",
    "url": "https://www.youtube.com/@tunhienhieuchuyen",
    "uploadsPlaylistId": "UUSISnv85eEjpBBBWxH2sgmA"
  },
  "total": 17,
  "videos": [
    {
      "id": "S6lmkU3GGqg",
      "videoId": "S6lmkU3GGqg",
      "title": "Món Ăn \"Dị\" Nhất Khiến Bạn Nổi Da Gà! #shorts",
      "url": "https://www.youtube.com/watch?v=S6lmkU3GGqg",
      "publishedAt": "2026-07-24T06:44:26Z",
      "description": "Thịt lợn treo xà nhà 30 năm đóng mạng nhện, gà ướp muối còn nguyên bộ lông hay da lợn nướng cháy đen thui... Bạn nghĩ đây là đồ bỏ đi? Thực ra đó là những cực phẩm ẩm thực siêu đắt đỏ đấy! Xem ngay để thử thách độ can đảm của chiếc bụng đói nhé!\n\n🔔 Bấm Đăng ký kênh để đón xem những điều kỳ lạ nhất thế giới mỗi ngày! 👇\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #AmThucKyDi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/S6lmkU3GGqg/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M13S",
      "durationSeconds": 73,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 287,
      "likeCount": 3,
      "commentCount": 2,
      "embeddable": true,
      "Tên Bài Hát": "Món Ăn \"Dị\" Nhất Khiến Bạn Nổi Da Gà! #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=S6lmkU3GGqg"
    },
    {
      "id": "U1PV96HOSP0",
      "videoId": "U1PV96HOSP0",
      "title": "BỊ ĐÁNH THỨC BỞI BOM BÓNG BAY VÀ CÁI KẾT BẤT NGỜ #shorts",
      "url": "https://www.youtube.com/watch?v=U1PV96HOSP0",
      "publishedAt": "2026-07-23T16:24:09Z",
      "description": "🎈 BOM BÓNG BAY + 🩸 MÁU GIẢ = 😱 PHA \"HẤP HỐI\" ĐỂ ĐỜI!\n\nĐang ngủ say như chết thì bị đánh thức bằng \"bom bóng bay\", chưa kịp check var xem mình còn sống hay chết thì \"bác sĩ rởm\" đã ập đến với đầy máu giả! \n\nVà cái kết... pha diễn xuất xứng đáng được đưa vào sách giáo khoa! 🏆\n\n👉 AE thấy video này thế nào? Comment cho mình biết nha! 👇\n\n#Prank #Comedy #Funny #HaiHuoc #Troll #Vietnam #BalloonPrank #FakeDoctor #10DiemKhongCoBut #CườiVỡBụng #Reels #FacebookReels\n\n#tunhienhieuchuyen #giaimavanvat #khampha #suthatthuvi",
      "thumbnail": "https://i.ytimg.com/vi/U1PV96HOSP0/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT51S",
      "durationSeconds": 51,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 34,
      "likeCount": 4,
      "commentCount": 1,
      "embeddable": true,
      "Tên Bài Hát": "BỊ ĐÁNH THỨC BỞI BOM BÓNG BAY VÀ CÁI KẾT BẤT NGỜ #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=U1PV96HOSP0"
    },
    {
      "id": "ySGNsGtGwrg",
      "videoId": "ySGNsGtGwrg",
      "title": "Chớp mắt Bộ Não Đang \"Lừa\" Bạn 20.000 Lần Mỗi Ngày! 👁️🧠",
      "url": "https://www.youtube.com/watch?v=ySGNsGtGwrg",
      "publishedAt": "2026-07-23T13:08:31Z",
      "description": "Mỗi ngày bạn chớp mắt 20.000 lần nhưng tại sao bạn không hề thấy bóng tối chớp tắt trước mắt? Đó là vì bộ não đã dùng một siêu năng lực tàng hình để giấu nhẹm điều đó khỏi bạn! Khám phá cơ chế kỳ diệu của đôi mắt và bộ não ngay trong video này.\n\n🔔 Bấm Đăng ký kênh để đón xem những bí ẩn cơ thể người cực thú vị mỗi ngày! 👇\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts\n#khampha #suthatthuvi",
      "thumbnail": "https://i.ytimg.com/vi/ySGNsGtGwrg/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M13S",
      "durationSeconds": 73,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 14,
      "likeCount": 5,
      "commentCount": 2,
      "embeddable": true,
      "Tên Bài Hát": "Chớp mắt Bộ Não Đang \"Lừa\" Bạn 20.000 Lần Mỗi Ngày! 👁️🧠",
      "Mã Video": "https://www.youtube.com/watch?v=ySGNsGtGwrg"
    },
    {
      "id": "cN0OcQKGzU8",
      "videoId": "cN0OcQKGzU8",
      "title": "Gặp “ma” giữa đường, sợ đến chân không đạp nổi xe XEM CHO VUI #shorts",
      "url": "https://www.youtube.com/watch?v=cN0OcQKGzU8",
      "publishedAt": "2026-07-23T12:10:50Z",
      "description": "Đang đạp xe giữa đường tối thì trước mặt xuất hiện hàng loạt “bóng trắng” đứng im không nhúc nhích. 😨\n\nTưởng sẽ bình tĩnh đi qua, ai ngờ vừa đến gần là chân mềm nhũn, chiếc xe cũng không còn nghe lời! Đoạn cố gắng đạp xe chạy thoát mới thật sự khiến người xem không nhịn được cười. 😂\n\nBạn gặp cảnh này thì còn đủ bình tĩnh để đạp xe tiếp không?\n\n\n#Shorts #HaiHuoc #TinhHuongHai #Prank #CuoiKhongNhatDuoc\n#tunhienhieuchuyen #giaimavanvat #khampha #suthatthuvi",
      "thumbnail": "https://i.ytimg.com/vi/cN0OcQKGzU8/sddefault.jpg",
      "thumbnailWidth": 640,
      "thumbnailHeight": 480,
      "duration": "PT41S",
      "durationSeconds": 41,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 1,
      "likeCount": 0,
      "commentCount": 1,
      "embeddable": true,
      "Tên Bài Hát": "Gặp “ma” giữa đường, sợ đến chân không đạp nổi xe XEM CHO VUI #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=cN0OcQKGzU8"
    },
    {
      "id": "zi9U5YAPEvY",
      "videoId": "zi9U5YAPEvY",
      "title": "Mặt Trời Không Dùng Oxy, Vậy Nó \"Bốc Cháy\" Bằng Cách Nào? ☀️⚛️#shorts",
      "url": "https://www.youtube.com/watch?v=zi9U5YAPEvY",
      "publishedAt": "2026-07-23T07:07:45Z",
      "description": "Bạn vẫn nghĩ Mặt Trời là một \"quả cầu lửa\" khổng lồ đang bốc cháy? Sai lầm rồi! Không gian Vũ trụ làm gì có oxy. Bí mật thực sự đằng sau nguồn năng lượng vĩnh cửu nuôi sống cả Trái Đất chính là phản ứng nhiệt hạch hạt nhân cực kỳ khủng khiếp. Cùng giải mã ngay nhé!\n\n🔔 Bấm Đăng ký kênh để đón xem những kiến thức khoa học vũ trụ kỳ thú mỗi ngày! 👇\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/zi9U5YAPEvY/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M20S",
      "durationSeconds": 80,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 793,
      "likeCount": 19,
      "commentCount": 1,
      "embeddable": true,
      "Tên Bài Hát": "Mặt Trời Không Dùng Oxy, Vậy Nó \"Bốc Cháy\" Bằng Cách Nào? ☀️⚛️#shorts",
      "Mã Video": "https://www.youtube.com/watch?v=zi9U5YAPEvY"
    },
    {
      "id": "g9R4ykD2MOA",
      "videoId": "g9R4ykD2MOA",
      "title": "Mẹo Xử Lý Vết Ong Đốt Sưng Tấy Cực Nhanh! 🐝🩹#shorts",
      "url": "https://www.youtube.com/watch?v=g9R4ykD2MOA",
      "publishedAt": "2026-07-22T14:30:34Z",
      "description": "Bị ong đốt sưng tấy đau nhức? Đừng dại dột dùng tay bóp ngòi ra kẻo nọc độc lan rộng hơn nhé! Xem ngay 5 bước sơ cứu vết ong đốt siêu đơn giản, chuẩn khoa học giúp giảm sưng dịu đau tức thì ngay tại nhà.\n\n🔔 Bấm Đăng ký kênh để đón xem những mẹo hay và kiến thức hữu ích mỗi ngày! 👇\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/g9R4ykD2MOA/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M17S",
      "durationSeconds": 77,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 916,
      "likeCount": 13,
      "commentCount": 1,
      "embeddable": true,
      "Tên Bài Hát": "Mẹo Xử Lý Vết Ong Đốt Sưng Tấy Cực Nhanh! 🐝🩹#shorts",
      "Mã Video": "https://www.youtube.com/watch?v=g9R4ykD2MOA"
    },
    {
      "id": "riOY995dlyc",
      "videoId": "riOY995dlyc",
      "title": "Đi Bộ Hay Chạy Bộ Giảm Mỡ Nhanh Hơn? Sự Thật Bất Ngờ! 🏃‍♂️🔥#shorts",
      "url": "https://www.youtube.com/watch?v=riOY995dlyc",
      "publishedAt": "2026-07-22T12:45:13Z",
      "description": "Cứ nghĩ chạy bộ hì hục đổ mồ hôi là siết mỡ tốt nhất? Khoa học lại chứng minh điều ngược lại! Khám phá bí mật về \"Vùng oxy hóa chất béo\" giúp bạn nhắm thẳng vào kho mỡ thừa chỉ bằng việc đi bộ. Đừng đâm đầu hành xác nữa, tập đúng cách để eo thon dáng gọn nhé!\n\n🔔 Bấm Đăng ký kênh để đón xem những kiến thức khoa học sức khỏe hữu ích mỗi ngày! 👇\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/riOY995dlyc/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT52S",
      "durationSeconds": 52,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 145,
      "likeCount": 15,
      "commentCount": 6,
      "embeddable": true,
      "Tên Bài Hát": "Đi Bộ Hay Chạy Bộ Giảm Mỡ Nhanh Hơn? Sự Thật Bất Ngờ! 🏃‍♂️🔥#shorts",
      "Mã Video": "https://www.youtube.com/watch?v=riOY995dlyc"
    },
    {
      "id": "uSngpnGNoPc",
      "videoId": "uSngpnGNoPc",
      "title": "Bí Ẩn Tiếng \"Sóng Biển\" Trong Vỏ Ốc - Tuổi Thơ Bị Lừa Rồi! 🐚🌊#shorts",
      "url": "https://www.youtube.com/watch?v=uSngpnGNoPc",
      "publishedAt": "2026-07-22T03:15:05Z",
      "description": "Nhặt vỏ ốc lên áp vào tai và nghe thấy tiếng \"sóng biển\" rì rào? Sự thật sẽ khiến bạn ngã ngửa vì vỏ ốc không hề biết phát ra âm thanh đâu! Cùng xem mẹ thiên nhiên đã làm \"ảo thuật\" thế nào nhé!\n\n🔔 Bấm Đăng ký kênh để đón xem những kiến thức thú vị mỗi ngày! 👇\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/uSngpnGNoPc/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT51S",
      "durationSeconds": 51,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 73,
      "likeCount": 7,
      "commentCount": 1,
      "embeddable": true,
      "Tên Bài Hát": "Bí Ẩn Tiếng \"Sóng Biển\" Trong Vỏ Ốc - Tuổi Thơ Bị Lừa Rồi! 🐚🌊#shorts",
      "Mã Video": "https://www.youtube.com/watch?v=uSngpnGNoPc"
    },
    {
      "id": "JzzWuy37rfY",
      "videoId": "JzzWuy37rfY",
      "title": "Tại Sao Tia Sét Lại Ngoằn Ngoèo Chứ Không Thẳng Tắp? ⚡🌩️#shorts",
      "url": "https://www.youtube.com/watch?v=JzzWuy37rfY",
      "publishedAt": "2026-07-22T00:56:10Z",
      "description": "Bạn nghĩ tia sét cứ thế đánh thẳng từ trên trời xuống đất? Sai lầm rồi! 🌩️ Bầu trời thực chất là một \"mê cung\" khổng lồ, và tia sét phải liên tục dò đường, bẻ lái zíc zắc để né những \"bức tường\" không khí cứng đầu. Xem ngay video để giải mã khoảnh khắc BÙM nổ ngoạn mục này diễn ra như thế nào nhé! 💥\n\n✈️ Gửi ngay cho hội bạn thân để xem ai trả lời đúng câu hỏi này trước khi xem video nào!\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts #xuhuong #khampha #hientuongtunhien",
      "thumbnail": "https://i.ytimg.com/vi/JzzWuy37rfY/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M22S",
      "durationSeconds": 82,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 771,
      "likeCount": 18,
      "commentCount": 1,
      "embeddable": true,
      "Tên Bài Hát": "Tại Sao Tia Sét Lại Ngoằn Ngoèo Chứ Không Thẳng Tắp? ⚡🌩️#shorts",
      "Mã Video": "https://www.youtube.com/watch?v=JzzWuy37rfY"
    },
    {
      "id": "iW3r7FIvaek",
      "videoId": "iW3r7FIvaek",
      "title": "Cú \"chôm bô\" đi vào lịch sử và phát minh phân bón NPK của Anh Hiểu Chuyện!",
      "url": "https://www.youtube.com/watch?v=iW3r7FIvaek",
      "publishedAt": "2026-07-21T15:42:28Z",
      "description": "Hành trình dở khóc dở cười của Anh Hiểu Chuyện khi vô tình khám phá ra công thức phân bón N-P-K (Đạm - Lân - Kali) đỉnh cao từ chiếc bô của cô hàng xóm! Cùng xem cách anh chàng tạo ra thần dược cho cây trồng nhé.\n\nĐừng quên bấm Đăng ký kênh để cùng giải mã thêm nhiều bài học khoa học thú vị mỗi ngày! 👇\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/iW3r7FIvaek/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT5M30S",
      "durationSeconds": 330,
      "isShortCandidate": false,
      "type": "video",
      "liveBroadcastContent": "none",
      "viewCount": 13,
      "likeCount": 4,
      "commentCount": 2,
      "embeddable": true,
      "Tên Bài Hát": "Cú \"chôm bô\" đi vào lịch sử và phát minh phân bón NPK của Anh Hiểu Chuyện!",
      "Mã Video": "https://www.youtube.com/watch?v=iW3r7FIvaek"
    },
    {
      "id": "O4AaHSWO2s0",
      "videoId": "O4AaHSWO2s0",
      "title": "Đại Kỵ Dùng Đũa Trên Bàn Tiệc - Cẩn Thận Kẻo \"Ăn Đòn\"! hiểu chuyện #shorts",
      "url": "https://www.youtube.com/watch?v=O4AaHSWO2s0",
      "publishedAt": "2026-07-21T14:52:00Z",
      "description": "Bạn có biết cắm đũa thẳng đứng vào bát cơm hay gõ bát đũa đinh đoong là những đại kỵ cực kỳ nghiêm trọng? Đôi đũa tuy nhỏ bé nhưng lại ẩn chứa cả một bầu trời triết lý nhân sinh phương Đông vô cùng sâu sắc. Cùng giải mã ngay để không bị \"tế\" trên bàn tiệc Tất niên nhé!\n\n🔔 Bấm Đăng ký kênh để không bỏ lỡ những kiến thức giải mã vạn vật cực cuốn mỗi ngày! 👇\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/O4AaHSWO2s0/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT2M59S",
      "durationSeconds": 179,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 1215,
      "likeCount": 11,
      "commentCount": 2,
      "embeddable": true,
      "Tên Bài Hát": "Đại Kỵ Dùng Đũa Trên Bàn Tiệc - Cẩn Thận Kẻo \"Ăn Đòn\"! hiểu chuyện #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=O4AaHSWO2s0"
    },
    {
      "id": "rE6F09pCFQY",
      "videoId": "rE6F09pCFQY",
      "title": "Động Đất Xảy Ra Như Thế Nào? Bí Mật Dưới Lòng Đất! 🌍💥#shorts",
      "url": "https://www.youtube.com/watch?v=rE6F09pCFQY",
      "publishedAt": "2026-07-21T05:32:02Z",
      "description": "Bạn có biết lớp vỏ Trái Đất không hề liền mạch mà được ghép từ nhiều mảnh khổng lồ đang trôi nổi? Khi chúng va chạm và vượt quá giới hạn chịu đựng, mặt đất sẽ rung chuyển! Cùng khám phá cơ chế thực sự gây ra động đất trong video này nhé.\n\nĐừng quên Đăng ký kênh để đón xem những kiến thức thú vị tiếp theo! 👇\nHashtag: #TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/rE6F09pCFQY/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M9S",
      "durationSeconds": 69,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 631,
      "likeCount": 8,
      "commentCount": 2,
      "embeddable": true,
      "Tên Bài Hát": "Động Đất Xảy Ra Như Thế Nào? Bí Mật Dưới Lòng Đất! 🌍💥#shorts",
      "Mã Video": "https://www.youtube.com/watch?v=rE6F09pCFQY"
    },
    {
      "id": "CS_7byroeCA",
      "videoId": "CS_7byroeCA",
      "title": "Sự Thật Đáng Sợ Về Thói Quen Ăn Đêm 😱 tunhienhieuchuyen #shorts",
      "url": "https://www.youtube.com/watch?v=CS_7byroeCA",
      "publishedAt": "2026-07-20T14:54:08Z",
      "description": "Bạn nghĩ ăn một chút cho no bụng rồi ngủ là vô hại? Thực tế, lúc đó các cơ quan nội tạng đang phải \"tăng ca\" đầy đau đớn. Năng lượng chuyển thành mỡ thừa, còn cơ thể thì bị vắt kiệt sức lực thay vì được nghỉ ngơi!\n\nĐừng quên đăng ký kênh để khám phá thêm nhiều điều thú vị nhé! 👇\nHashtag: #TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucMoiNgay #KhoaHocDoiSong #HocMaChoi #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/CS_7byroeCA/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M14S",
      "durationSeconds": 74,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 861,
      "likeCount": 18,
      "commentCount": 3,
      "embeddable": true,
      "Tên Bài Hát": "Sự Thật Đáng Sợ Về Thói Quen Ăn Đêm 😱 tunhienhieuchuyen #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=CS_7byroeCA"
    },
    {
      "id": "SvYIQufvCqQ",
      "videoId": "SvYIQufvCqQ",
      "title": "Vì sao khóc không phải là cách để giải quyết vấn đề #shorts",
      "url": "https://www.youtube.com/watch?v=SvYIQufvCqQ",
      "publishedAt": "2026-07-20T03:30:36Z",
      "description": "Dừng việc khóc lại nếu bạn chưa biết điều này! 🛑\r\n\r\nKhóc là cơ chế tự nhiên giúp xả stress, nhưng nó KHÔNG giải quyết được gốc rễ của vấn đề. Video này sẽ bóc tách sự thật đằng sau những giọt nước mắt và hướng dẫn bạn cách chuyển hóa sự ấm ức thành hành động thực tế.\r\nĐừng để những rắc rối tiếp tục cản bước bạn! 🚀\r\n\r\n👉 Xem ngay để thay đổi tư duy và tìm ra giải pháp!\r\n#TuDuyLogic #KhoaHoc #GiaiQuyetVanDe #KienThucMoi\n\n00:00 - Câu hỏi chính\r\n00:15 - Cơ chế phía sau\r\n00:45 - Điều đáng nhớ\n\n#TuNhienHieuChuyen #GiaiMaVanVat #CauHoiViSao #KienThucVui #KhoaHocDoiSong #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/SvYIQufvCqQ/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT58S",
      "durationSeconds": 58,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 30,
      "likeCount": 5,
      "commentCount": 4,
      "embeddable": true,
      "Tên Bài Hát": "Vì sao khóc không phải là cách để giải quyết vấn đề #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=SvYIQufvCqQ"
    },
    {
      "id": "uXFnERktJek",
      "videoId": "uXFnERktJek",
      "title": "Bạn đã từng thấy mặt trời kỳ lạ này chưa? Vì sao lại thế #shorts",
      "url": "https://www.youtube.com/watch?v=uXFnERktJek",
      "publishedAt": "2026-07-20T01:55:10Z",
      "description": "Có lúc Mặt Trời trông như bị cắt mất một phần, nhưng đó không hẳn là điều bí ẩn trên bầu trời.\r\n\r\nVideo này gợi mở cách mây, góc nhìn và ánh sáng có thể khiến một cảnh rất quen thuộc trông lạ hơn bình thường.\r\n\r\nBạn từng thấy Mặt Trời hoặc Mặt Trăng nhìn kỳ lạ như vậy chưa?\n\n00:00 - Câu hỏi chính\r\n00:15 - Cơ chế phía sau\r\n00:45 - Điều đáng nhớ\n\n#TuNhienHieuChuyen #MatTroi #HienTuongThienNhien #KhoaHocDoiSong #KienThucVui #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/uXFnERktJek/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M33S",
      "durationSeconds": 93,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 883,
      "likeCount": 15,
      "commentCount": 4,
      "embeddable": true,
      "Tên Bài Hát": "Bạn đã từng thấy mặt trời kỳ lạ này chưa? Vì sao lại thế #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=uXFnERktJek"
    },
    {
      "id": "SmgjfmbplSM",
      "videoId": "SmgjfmbplSM",
      "title": "Có thể bạn nhìn thấy nó mỗi ngày nhưng chưa từng hiểu đúng #shorts",
      "url": "https://www.youtube.com/watch?v=SmgjfmbplSM",
      "publishedAt": "2026-07-18T13:42:26Z",
      "description": "Tự Nhiên Hiểu Chuyện - nơi giải mã những hiện tượng quen thuộc quanh ta bằng cách ngắn gọn, dễ hiểu và thú vị.\r\n\r\nVideo đầu tiên mở màn cho chuỗi “Giải mã vạn vật mỗi ngày”. Nếu bạn muốn kênh giải thích hiện tượng nào tiếp theo, hãy để lại bình luận bên dưới.\r\n\r\n#tunhienhieuchuyen #giaimavanvat #kienthuc #khoahocvui #shorts\n\n\n\n#tunhienhieuchuyen #giaimavanvat #kienthuc #khoahocvui #shorts",
      "thumbnail": "https://i.ytimg.com/vi/SmgjfmbplSM/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT59S",
      "durationSeconds": 59,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 33,
      "likeCount": 6,
      "commentCount": 5,
      "embeddable": true,
      "Tên Bài Hát": "Có thể bạn nhìn thấy nó mỗi ngày nhưng chưa từng hiểu đúng #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=SmgjfmbplSM"
    },
    {
      "id": "0JLxdN-oP3E",
      "videoId": "0JLxdN-oP3E",
      "title": "Vì sao chúng ta lại xì hơi? Sự thật ai cũng từng gặp #shorts",
      "url": "https://www.youtube.com/watch?v=0JLxdN-oP3E",
      "publishedAt": "2026-07-18T13:29:50Z",
      "description": "Vì sao chúng ta lại xì hơi? Đây là hiện tượng rất bình thường của cơ thể khi tiêu hóa thức ăn.\r\n\r\nKhi thức ăn được phân giải trong ruột, khí có thể sinh ra và cần được đưa ra ngoài. Vì vậy xì hơi không phải lúc nào cũng là chuyện xấu hổ, mà là một phần tự nhiên của quá trình tiêu hóa.\r\n\r\nTự Nhiên Hiểu Chuyện giải mã những điều quen thuộc quanh ta bằng cách ngắn gọn, dễ hiểu và thú vị.\r\n\r\nBạn muốn kênh giải thích hiện tượng cơ thể nào tiếp theo? Hãy để lại bình luận nhé.\r\n\r\n#TuNhienHieuChuyen #GiaiMaVanVat #KienThucVui #SucKhoe #Shorts\n\n\n\n#TuNhienHieuChuyen #GiaiMaVanVat #KienThucVui #SucKhoe #Shorts",
      "thumbnail": "https://i.ytimg.com/vi/0JLxdN-oP3E/maxresdefault.jpg",
      "thumbnailWidth": 1280,
      "thumbnailHeight": 720,
      "duration": "PT1M22S",
      "durationSeconds": 82,
      "isShortCandidate": true,
      "type": "short_candidate",
      "liveBroadcastContent": "none",
      "viewCount": 28,
      "likeCount": 6,
      "commentCount": 3,
      "embeddable": true,
      "Tên Bài Hát": "Vì sao chúng ta lại xì hơi? Sự thật ai cũng từng gặp #shorts",
      "Mã Video": "https://www.youtube.com/watch?v=0JLxdN-oP3E"
    }
  ]
};
  w.LIFEOS_YOUTUBE_SYNC = data;
  w.LIFEOS_YOUTUBE_VIDEOS = data.videos;
})(window);
